### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by tieSari** [juhohei/rebel#1]
Koodi ladattu 15.8. klo 18:30

Plussat
Rebel-master -pelin koodaamisessa oli käytetty lyhyitä ja selkeitä yhden asian metodeita.

Ominaisuudet Direction, Size ja Position oli toteutettu selkeinä luokkina eikä esim. vakioina tai taulukoina.

Samoja toiminnallisuuksia sisältävät luokat oli periytetty yliluokasta Movable, ei ollut turhaa toistoa.

Koodaamisessa oli käytetty Javan 8-versiota. En ole itse vielä koodannut sillä ja nyt oli pakko asentaa se, mikä oli pelkästään hyvä asia :) Movable-luokassa foreach-loopissa käytetty metodiviittaus näytti näppärältä ja selkeältä.
 
Miinukset

Koodia oli vielä melko vähän, eikä ohjelmaa vielä voinut ajaa. Testejä oli vain kaksi, eikä toinen mennyt kääntäjästä läpi. Luokkakaavio olisi helpottanut koodiin tutustumista.

Ehkä luokkia voisi jakaa useampaan pakettiin. Nyt rebel.models -paketissa on sekä apuluokkia että logiikkaa sisältäviä luokkia. Siirtäisin Size, Position ja Direction -luokat omaan pakettiinsa, esim. rebels.helpers tms.

**Comment by juhohei** [comment]
Kiitti palautteesta!

En oo kauheesti pystynyt irrottamaan aikaa tämän tekemiseen, joten koodia ei kauheesti vielä ole. Testit ei mene läpi, koska ne on edellisestä commitista, jonka jälkeen olen muuttanut logiikkaa. Pistän ne kuntoon seuraavaksi.

Paketit on tarkoitus jakaa seuraavasti: rebel.models (logiikka), rebel.controllers (näppäinkuuntelijat), rebel.utils (apufunktiot) ja rebel.views (gui). Omasta mielestäni ainakin järkeenkäypä rakenne, mikä ei tosin kyllä vielä tule projektin nykytilasta esille :)

Luokkakaavio ei (varsinkaan tämän kokoisessa) projektissa herätä itsessäni innostusta, mutta kaipa sekin pitää jossain vaiheessa tehdä, kun niin vaaditaan.
